const nodemailer = require('nodemailer');
const QRCode = require('qrcode');
const { createCanvas, loadImage } = require('canvas');
const fs = require('fs');
const logger = require('../utils/logger');
const AppError = require('../utils/AppError');

class EmailService {
    constructor() {
        this.transporter = null;
        this.init();
    }

    async init() {
        // Simple, direct configuration from Environment Variables
        const config = {
            host: process.env.SMTP_HOST || 'smtp.gmail.com',
            port: parseInt(process.env.SMTP_PORT || '465'),
            secure: process.env.SMTP_SECURE === 'true' || true,
            auth: {
                user: process.env.SMTP_USER,
                pass: process.env.SMTP_PASS
            }
        };

        if (!config.auth.user || !config.auth.pass) {
            logger.warn("[Email] Credentials missing in .env");
            return;
        }

        this.transporter = nodemailer.createTransport({
            ...config,
            // Standard timeouts
            connectionTimeout: 10000, 
            socketTimeout: 10000
        });

        try {
            await this.transporter.verify();
            logger.info(`[Email] Ready. Connected as ${config.auth.user}`);
        } catch (error) {
            logger.error(`[Email] Connection Failed: ${error.message}`);
            this.transporter = null;
        }
    }

    async generateTicketImage(ticket, bgPath, config = {}) {
        // Defaults
        const qrSize = parseInt(config.qrSize || 1150);
        const qrX = parseInt(config.qrX || 220);
        const qrY = parseInt(config.qrY || 1110);
        const fontSize = parseInt(config.fontSize || 150);
        const nameX = parseInt(config.nameX || 400);
        const nameY = parseInt(config.nameY || 925);

        // 1. Background
        let image;
        if (bgPath && fs.existsSync(bgPath)) {
            image = await loadImage(bgPath);
        } else {
            const canvas = createCanvas(2480, 3508); // A4
            const ctx = canvas.getContext('2d');
            ctx.fillStyle = 'white';
            ctx.fillRect(0, 0, 2480, 3508);
            image = canvas;
        }

        const canvas = createCanvas(image.width, image.height);
        const ctx = canvas.getContext('2d');
        ctx.drawImage(image, 0, 0);

        // 2. QR Code
        const qrDataUrl = await QRCode.toDataURL(ticket.id, {
            errorCorrectionLevel: 'H', margin: 0, width: qrSize,
            color: { dark: '#000000', light: '#ffffff' }
        });
        const qrImg = await loadImage(qrDataUrl);
        ctx.drawImage(qrImg, qrX, qrY, qrSize, qrSize);

        // 3. Name Text
        const nameText = ticket.attendeeName || "Unknown";
        ctx.font = `bold ${fontSize}px Arial`;
        
        // Center the text horizontally on the image
        ctx.textAlign = 'center';
        ctx.textBaseline = 'top';
        
        const centerX = canvas.width / 2;

        ctx.lineWidth = Math.floor(fontSize * 0.05);
        ctx.strokeStyle = 'white';
        ctx.fillStyle = 'black';

        ctx.strokeText(nameText, centerX, nameY);
        ctx.fillText(nameText, centerX, nameY);

        // Watermark
        ctx.save();
        ctx.font = '20px Arial';
        ctx.fillStyle = 'rgba(100, 100, 100, 0.5)';
        ctx.textAlign = 'right';
        ctx.fillText('Generated by NullifiedGalaxy', canvas.width - 20, canvas.height - 20);
        ctx.restore();

        return canvas.toBuffer('image/png');
    }

    async sendTicketEmail(ticket, eventId, bgPath, config = {}) {
        if (!this.transporter) await this.init();
        if (!this.transporter) throw new AppError("Email service not configured", 500);

        const imageBuffer = await this.generateTicketImage(ticket, bgPath, config);
        const cid = `ticket-${ticket.id}@ticketsystem.local`;

        // Default messages
        const msgBefore = config.messageBefore ? config.messageBefore.replace(/\n/g, '<br>') : `Here is your ticket for <strong>${eventId}</strong>.`;
        const msgAfter = config.messageAfter ? config.messageAfter.replace(/\n/g, '<br>') : "Please present this QR code at the entrance.";

        const mailOptions = {
            from: `"Ticket System" <${this.transporter.transporter.auth.user}>`,
            to: ticket.attendeeEmail,
            subject: `Your Ticket for ${eventId}`,
            html: `
                <div style="font-family: sans-serif; text-align: center; background: #f4f4f4; padding: 0; margin: 0;">
                    <div style="background: white; padding: 40px 20px; border-radius: 0; max-width: 600px; margin: auto;">
                        
                        <h2 style="color: #333; margin-bottom: 20px;">Hello ${ticket.attendeeName},</h2>
                        
                        <p style="color: #555; font-size: 16px; line-height: 1.5; margin-bottom: 20px;">
                            ${msgBefore}
                        </p>

                        <div style="margin: 30px 0; width: 100%;">
                            <img src="cid:${cid}" style="width: 100%; height: auto; display: block; border: 1px solid #eee; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">
                        </div>

                        <p style="color: #555; font-size: 16px; line-height: 1.5; margin-bottom: 30px;">
                            ${msgAfter}
                        </p>
                        
                        <p style="color: #aaa; font-size: 12px; margin-top: 40px; border-top: 1px solid #eee; padding-top: 20px;">
                            Ticket ID: ${ticket.id}
                        </p>
                    </div>
                </div>
            `,
            attachments: [{ filename: 'ticket.png', content: imageBuffer, cid: cid }]
        };

        const info = await this.transporter.sendMail(mailOptions);
        logger.info(`[Email] Sent to ${ticket.attendeeEmail}`);
        return info;
    }

    async getPreviewImage(ticket, bgPath, config) {
        const buffer = await this.generateTicketImage(ticket, bgPath, config);
        return `data:image/png;base64,${buffer.toString('base64')}`;
    }
}

module.exports = new EmailService();